import java.util.Scanner;
import java.math.BigInteger;
import java.security.*;

public class hw6 {

    public static String getSHA(String input) {

        try {

            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashTxt = no.toString(16);

            while(hashTxt.length() < 32) {
                hashTxt = "0" + hashTxt;
            }

            return hashTxt;
            
        } catch (Exception e) {
            System.out.println("Exception thrown"
                               + " for incorrect algorithm: " + e); 
  
            return null; 
        }
    }

    public static void main(String[] args) throws NoSuchAlgorithmException {

        String arr[] = new String[8];
        String lvl1HashArr[] = new String[8];
        String lvl2HashArr[] = new String[4];
        String lvl3HashArr[] = new String[2];
        String rootHashArr[] = new String[1];
        System.out.println("HashCode Generated by SHA-256 for:"); 
  
        for (int i = 0; i < arr.length; ++i) {

            System.out.println("Enter a 4 letter word: ");
            Scanner scanner = new Scanner(System.in);
            String msg = scanner.nextLine();

            while(msg.length() > 4) {
                System.out.println("------------------------------------------");
                System.out.println("The String must be of length 4. Try Again.");
                System.out.println("Enter a 4 letter word: ");
                System.out.println("------------------------------------------");
                scanner = new Scanner(System.in);
                msg = scanner.nextLine();
                System.out.println(" ");
            }

            arr[i] = msg;
            lvl1HashArr[i] = getSHA(arr[i]);
            // System.out.println("\n" + m1 + " : " + getSHA(m1)); 
        }

        lvl2HashArr[0] = getSHA(lvl1HashArr[0] + lvl1HashArr[1]);
        System.out.println(lvl1HashArr[0] + lvl1HashArr[1]);
        System.out.println(lvl2HashArr[0]);

        // for (int i = 0; i < arr.length; ++i) {
        //     System.out.println(i + ") " + arr[i]);
        //     System.out.println(hashArr[i]);
        // }
    
        // String s2 = "hell"; 
        // System.out.println("\n" + s2 + " : " + getSHA(s2)); 
    }
}